### ISSUE TITLE
Do you have any examples of options?

### ISSUE THREAD

**Issue by santarone** [sidebase/nuxt-pdf#16]
### Ask your question

According to the Quick Start Guide, there is a section to refer to 'document options'.
You can see that the link is connected to the official jsPDF document.

From nupt3
`import { exportToPDF } from '#imports'`

I understand that you use it as a phrase.
Can you tell me an example where I can put detailed options based on the jsPDF document?

**Comment by Jorgagu** [comment]
Hi @santarone, in the documentation you have the link to specific content for both of the parameters `documentOptions` (jsPDF) and `options` (html2canvas).

But if you need example you can look at this one here: https://github.com/sidebase/nuxt-pdf/blob/main/playground/app.vue#L31

**Comment by zoey-kaiser** [comment]
Hi @santarone 👋 

I just updated the docs to be a little bit more precise on this. You can find them here: https://sidebase.io/nuxt-pdf/application-side/composables#options

Otherwise you can also directly view the jspdf docs about each option type here:
- documentOptions: http://raw.githack.com/MrRio/jsPDF/master/docs/jsPDF.html
- htmlOptions: http://raw.githack.com/MrRio/jsPDF/master/docs/module-html.html#~html
